package views;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import javax.swing.ListModel;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        form.setVisible(false);
    }

    //Getters and Setters
    public void setFormVisibility(boolean flag) {
        form.setVisible(flag);
    }

    public void setAreaValue(String areaValue) {
        this.areaValue.setText(areaValue);
    }

    public String getParamOne() {
        paramOneError.setText("");
        return paramOne.getText();
    }
    
    public void setParamOne(String paramOne) {
        this.paramOne.setText(paramOne);
    }

    public void setParamOneLabel(String paramOneLabel) {

        this.paramOneLabel.setText(paramOneLabel);
    }

    public void setParamOneError(String paramOneError) {
        this.paramOneError.setText(paramOneError);
    }

    public void setParamOneFieldVisibility(boolean flag) {
        paramOne.setVisible(flag);
    }

    public String getParamTwo() {
        paramTwoError.setText("");
        return paramTwo.getText();
    }
    
    public void setParamTwo(String paramTwo) {
        this.paramTwo.setText(paramTwo);
    }

    public void setParamTwoLabel(String paramTwoLabel) {
        this.paramTwoLabel.setText(paramTwoLabel);
    }

    public void setParamTwoFieldVisibility(boolean flag) {
        paramTwo.setVisible(flag);
    }

    public void setParamTwoError(String paramTwoError) {
        this.paramTwoError.setText(paramTwoError);
    }

    public String getShapeType() {
        return (String) shapeType.getSelectedItem();
    }

    public void addCalculateActionListener(ActionListener listener) {
        calculate.addActionListener(listener);
    }

    public void addShapeTypeActionListener(ActionListener listener) {
        shapeType.addActionListener(listener);
    }

    public void addListKeyListener(KeyListener listener) {
        polygonList.addKeyListener(listener);
    }

    public int getListSelectedIndex() {
        return polygonList.getSelectedIndex();
    }

    public void setPolygonList(ListModel polygonList) {
        this.polygonList.setModel(polygonList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shapeType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        polygonList = new javax.swing.JList();
        form = new javax.swing.JPanel();
        paramOneLabel = new javax.swing.JLabel();
        paramTwoLabel = new javax.swing.JLabel();
        paramOne = new javax.swing.JTextField();
        paramTwo = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        areaValue = new javax.swing.JLabel();
        paramOneError = new javax.swing.JLabel();
        paramTwoError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Shape:");

        shapeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Triangle", "Ellipse", "Square", "Rhombus", "Circle" }));

        jLabel5.setText("List Of Shapes");

        polygonList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(polygonList);

        paramOneLabel.setText("Base:");

        paramTwoLabel.setText("Height:");

        calculate.setText("Calculate");

        jLabel4.setText("Area:");

        areaValue.setText("Value");

        paramOneError.setText("Error");

        paramTwoError.setText("Error");

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(areaValue))
                            .addGroup(formLayout.createSequentialGroup()
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paramTwoLabel)
                                    .addComponent(paramOneLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paramOne, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(paramTwo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paramOneError)
                                    .addComponent(paramTwoError)))))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(calculate)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramOneLabel)
                    .addComponent(paramOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramOneError))
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramTwoLabel)
                    .addComponent(paramTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramTwoError))
                .addGap(18, 18, 18)
                .addComponent(calculate)
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(areaValue))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(shapeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(282, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(shapeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaValue;
    private javax.swing.JButton calculate;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField paramOne;
    private javax.swing.JLabel paramOneError;
    private javax.swing.JLabel paramOneLabel;
    private javax.swing.JTextField paramTwo;
    private javax.swing.JLabel paramTwoError;
    private javax.swing.JLabel paramTwoLabel;
    private javax.swing.JList polygonList;
    private javax.swing.JComboBox shapeType;
    // End of variables declaration//GEN-END:variables
}
